# Default values for arm64v8-btcrpcexplorer
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jkaldon/arm64v8-lnd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.14.2-beta-5"
#  command: ["/bin/cat"]
#  stdin: true 
#  tty: true
#  lifecycle:
#    preStop:
#      exec:
#        command: []

envFrom:
- secretRef:
    name: lnd-rpc-creds

#
#initEnv:
#- name: RPC_USERNAME
#  value: "username"
#- name: RPC_PASSWORD
#  value: "password"

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim:
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: nfs-client
  annotations: {}
  accessMode: "ReadWriteOnce"
  size: "8Gi"
  volumes:
  - name: lnd-data
    persistentVolumeClaim:
      claimName: lnd
  mounts:
  - name: lnd-data
    mountPath: /data
    readOnly: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http

